### ISSUE TITLE
Reproject.jl slower than Astropy's reproject

### ISSUE THREAD

**Issue by jmbhughes** [JuliaAstro/Reproject.jl#16]
Hi!

I noticed the Julia implementation was slower than the Python implementation. I was curious if you had any insight as to why this might be.

The following Julia code takes 38 seconds to run on my laptop:
```jl
using Reproject, FITSIO
using Dates

start = now()
input_data = FITS("gc_msx_e.fits")
output_projection = FITS("gc_2mass_k.fits")

for i in 1:10
    result = reproject(input_data, output_projection, shape_out = (1000,1000), order = 2, hdu_in = 1, hdu_out = 1)
end

stop = now()

println(stop - start)
```

The equivalent Python code takes 3 seconds:

```py
import reproject
from astropy.io import fits
from astropy.wcs import WCS
import time

start = time.time()
input_data = fits.open("gc_msx_e.fits")
output_data = fits.open("gc_2mass_k.fits")
output_projection = WCS(output_data[0].header)

for _ in range(10):
    result = reproject.reproject_interp(input_data, output_projection, shape_out = (1000, 1000), 
                                        hdu_in=0, order='biquadratic')
stop = time.time()

print(stop - start)
```

I'm very new to Julia so I'm trying to learn and may be missing something obvious. Thanks!

**Comment by giordano** [comment]
To set expectations clear, this package hasn't got much love lately, and while it was initially created for [`AstroImages.jl`](https://github.com/JuliaAstro/AstroImages.jl), that package doesn't use `Reproject.jl` anymore, so it's unlikely it'll get much more attention or further improvements.

**Comment by jmbhughes** [comment]
Okay thanks for letting me know.

**Comment by giordano** [comment]
Sorry, I forgot to add a couple of comments more:

* if you have concrete improvements, like #15, they may still be accepted, just don't expect others to resolve open issues
* to answer your question about why this code is much slower than the corresponding python code, it has been a long time since I last looked at this code, but it was probably not particularly optimised for performance, so extra memory allocations or type-instabilities may be around.  Per the point above, if anyone is willing to fix those, they're more than welcome!
